### ISSUE TITLE
Small typo in sosseq.jl causes the thing to crash

### ISSUE THREAD

**Issue by clagms** [blegat/SwitchOnSafety.jl#4]
I think that, in sosseq.jl, line 89:
```
Z = monomials(variables(s, curstate), d)
```
should be
```
Z = monomials(**_**variables(s, curstate), d)
```

**Comment by blegat** [comment]
I just fixed it on the moi branch. Aren't you using the master branch ?

**Comment by blegat** [comment]
Forget what I said, I fixed it on the master branch too now :)
