### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by BotYue** [blegat/SwitchOnSafety.jl#8]
Hi There,
I attempted to install this package. However, I encountered the following error.  
`julia> Pkg.clone("git://github.com/blegat/SwitchOnSafety.jl.git")`
```
ERROR: The following package names could not be resolved:
 * SetProg (not found in project, manifest or registry)
Please specify by known `name=uuid`.
```

**Comment by blegat** [comment]
The current version relies on [`SetProg`](https://github.com/blegat/SetProg.jl) which is not released yet. I have update the README in 2cc4664a4acfcfe9c351180ac4e44f69a07d4a14. Then for letting me know !
